name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # change this depending on security policies, see: https://github.com/aws-actions/configure-aws-credentials 
    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform Backend Infrastructure
      run: |
        cd infra
        ./setup_backend.sh

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.6.3"

    - name: Clear Terraform Cache
      run: |
        cd infra
        rm -rf .terraform

    - name: Terraform Init and Apply
      run: |
        cd infra
        if [ "$GITHUB_REF" == "refs/heads/main" ]; then
          terraform init
          terraform workspace select prod
          terraform apply -auto-approve -var-file="prod.tfvars"
        elif [ "$GITHUB_REF" == "refs/heads/develop" ]; then
          terraform init
          terraform workspace select dev
          terraform apply -auto-approve -var-file="dev.tfvars"
        fi
